version: "3"

services:
  torneos:
    container_name: torneos
    image: torneos
    ports:
      - "3000:3000"
    environment:
      - ENDPOINT_USER = "http://34.67.137.28:30022"
      - ENDPOINT_TORNEOS = "http://34.67.137.28:3000"
      - ENDPOINT_TOKENS = "http://35.225.47.35:5001"
      - ENDPOINT_DADOS = "http://35.225.47.35:5002"
      - ID_USER = "Usuarios"
      - SECRET_USER = "UsuariosSecret"
      - ID_TORNEOS = "Torneo"
      - SECRET_TORNEOS = "TorneoSecret"
      - ID_DADOS = "Dados"
      - SECRET_DADOS = "DadosSecret"
      - ID_JUEGO = "Juego"
      - SECRET_JUEGOS = "JuegoSecret"
  usuarios:
    container_name: usuarios
    image: usuarios
    ports:
      - "3002:3002"
  webapp:
    container_name: webapp
    image: frontend
    ports:
      - "80:80"